nurse911/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Login;
use app\models\ContactForm;
use app\models\Conversion;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    //renders the index page
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest) {
            $this->layout='guest';
        } else {
            $this->layout='main';
        }
        return $this->render('index');
    }

}

nurse911/controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout='guest';

        $model = new User();

        if ($model->load(Yii::$app->request->post())) {

            $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            $model->save();
            return $this->redirect(['login', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    //Logs the specified user in.
    public function actionLogin()
    {
        if(Yii::$app->user->isGuest) {
            $this->layout='guest';
        } else {
            $this->layout='main';
        }

        $request = Yii::$app->request;

        if ($request->isPost) {
            $username =  $request->post('username');
            $password = $request->post('password');

            $model = User::findByUsername($username);

            if (Yii::$app->getSecurity()->validatePassword($password, $model['password'])) {
                Yii::$app->user->login($model, 0);
                return $this->redirect(['site/index']);
            } else {
                return $this->refresh();
            }

        } else {
            return $this->render('login');
        }
    }

    //logs the user out
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['/site/index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

nurse911/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
/* This is the error page.*/

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

nurse911/views/site/index.php
<?php

use yii\helpers\Html;

$this->title = 'Nurse911';
/* This is the home page for the application */
?>

<section class="container" id="indexPage">
    <?= Html::img('@web/images/nurses.jpg', ['alt' => 'Some Nurses', 'class' => 'img-responsive']) ?>
    <h1>Welcome to Nurse911</h1>

    <article class="col-sm-8">
        <h3>We're here to help!</h3>
        <p>All nurses, from the first-year student to the seasoned veteran need help occasionally. Whether you need help with conversions, a reference for scales, or
        just a convenient place to store important numbers, Nurse911 has got your back. Let us do the trivial stuff for you, so you can focus on what's really
        important: <em>your patients.</em></p>
    </article>

    <article class="col-sm-4 callToAction">
       <h3>Join us!</h3>
        <div class="buttons">
            <div id="left">
                <p>Not a Member?</p>
                <?= Html::a('Sign Up', ['user/create'], ['class' => 'btn btn-red']) ?>
            </div>
            <div id="right">
                <p>Returning Member?</p>
                <?= Html::a('Login', ['user/login'], ['class' => 'btn btn-red']) ?>
            </div>
        </div>

    </article>
</section>